#!/usr/bin/env node

"use strict";

let fs = require("fs");
let config = require('./conf/config');

let inter = setInterval(() => {
    console.log('check cron.json');

    let appPath = process.env.APP_PATH;
    // let appPath = __dirname;
    if (!appPath) {
        return;
    }
    let cronFile = appPath + '/cron.json';
    if (!fs.existsSync(cronFile)) {
        return;
    }
    let content = fs.readFileSync(cronFile);
    if (content) {
        console.log('checked');
        clearInterval(inter);
        exec(content);
    }
}, 3000);


function exec(json) {
    config.name = process.env.APP_NAME;
    config.webhook = process.env.APP_MONITOR_HOOK;

    let data = JSON.parse(json);
    if (!data) {
        process.exit('json parse error');
    }

    let server = require('./service/task/server');
    server.start(data);
}
