#!/usr/bin/env node

let fs = require("fs");
let config = require('./conf/config');

let appPath = process.env.APP_PATH;
// let appPath = __dirname;
if (!appPath) {
    process.exit('app path null');
}

let inter = setInterval(() => {
    "use strict";

    console.log('check cron.json');
    let content = fs.readFileSync(appPath + '/cron.json');
    if (content) {
        console.log('checked');
        clearInterval(inter);
        exec(content);
    }
}, 3000);


function exec(json) {
    "use strict";

    config.name = process.env.APP_NAME;
    config.webhook = process.env.APP_MONITOR_HOOK;

    let data = JSON.parse(json);
    if (!data) {
        process.exit('json parse error');
    }

    let server = require('./service/task/server');
    server.start(data);
}
